export const TIMEZONES = [
  { label: 'Eastern Time (ET) - USA/Canada', value: 'America/New_York' },
  { label: 'Central Time (CT) - USA/Canada', value: 'America/Chicago' },
  { label: 'Mountain Time (MT) - USA/Canada', value: 'America/Denver' },
  { label: 'Pacific Time (PT) - USA/Canada', value: 'America/Los_Angeles' },
  { label: 'Alaska (AKT) - USA', value: 'America/Anchorage' },
  { label: 'Hawaii (HST) - USA', value: 'Pacific/Honolulu' },
  { label: 'Arizona (MST) - USA', value: 'America/Phoenix' },
  { label: 'London - UK', value: 'Europe/London' },
  { label: 'Dublin - Ireland', value: 'Europe/Dublin' },
  { label: 'Lisbon - Portugal', value: 'Europe/Lisbon' },
  { label: 'Paris - France', value: 'Europe/Paris' },
  { label: 'Berlin - Germany', value: 'Europe/Berlin' },
  { label: 'Rome - Italy', value: 'Europe/Rome' },
  { label: 'Madrid - Spain', value: 'Europe/Madrid' },
  { label: 'Amsterdam - Netherlands', value: 'Europe/Amsterdam' },
  { label: 'Brussels - Belgium', value: 'Europe/Brussels' },
  { label: 'Zurich - Switzerland', value: 'Europe/Zurich' },
  { label: 'Stockholm - Sweden', value: 'Europe/Stockholm' },
  { label: 'Oslo - Norway', value: 'Europe/Oslo' },
  { label: 'Copenhagen - Denmark', value: 'Europe/Copenhagen' },
  { label: 'Helsinki - Finland', value: 'Europe/Helsinki' },
  { label: 'Vienna - Austria', value: 'Europe/Vienna' },
  { label: 'Prague - Czech Republic', value: 'Europe/Prague' },
  { label: 'Warsaw - Poland', value: 'Europe/Warsaw' },
  { label: 'Budapest - Hungary', value: 'Europe/Budapest' },
  { label: 'Athens - Greece', value: 'Europe/Athens' },
  { label: 'Istanbul - Turkey', value: 'Europe/Istanbul' },
  { label: 'Moscow - Russia', value: 'Europe/Moscow' },
  { label: 'Dubai - UAE', value: 'Asia/Dubai' },
  { label: 'Riyadh - Saudi Arabia', value: 'Asia/Riyadh' },
  { label: 'Doha - Qatar', value: 'Asia/Qatar' },
  { label: 'Kuwait City - Kuwait', value: 'Asia/Kuwait' },
  { label: 'Muscat - Oman', value: 'Asia/Muscat' },
  { label: 'Mumbai - India', value: 'Asia/Kolkata' },
  { label: 'Karachi - Pakistan', value: 'Asia/Karachi' },
  { label: 'Lahore - Pakistan', value: 'Asia/Karachi' },
  { label: 'Islamabad - Pakistan', value: 'Asia/Karachi' },
  { label: 'Dhaka - Bangladesh', value: 'Asia/Dhaka' },
  { label: 'Colombo - Sri Lanka', value: 'Asia/Colombo' },
  { label: 'Kathmandu - Nepal', value: 'Asia/Kathmandu' },
  { label: 'Singapore', value: 'Asia/Singapore' },
  { label: 'Kuala Lumpur - Malaysia', value: 'Asia/Kuala_Lumpur' },
  { label: 'Jakarta - Indonesia', value: 'Asia/Jakarta' },
  { label: 'Bangkok - Thailand', value: 'Asia/Bangkok' },
  { label: 'Ho Chi Minh - Vietnam', value: 'Asia/Ho_Chi_Minh' },
  { label: 'Manila - Philippines', value: 'Asia/Manila' },
  { label: 'Hong Kong', value: 'Asia/Hong_Kong' },
  { label: 'Shanghai - China', value: 'Asia/Shanghai' },
  { label: 'Taipei - Taiwan', value: 'Asia/Taipei' },
  { label: 'Seoul - South Korea', value: 'Asia/Seoul' },
  { label: 'Tokyo - Japan', value: 'Asia/Tokyo' },
  { label: 'Tehran - Iran', value: 'Asia/Tehran' },
  { label: 'Baghdad - Iraq', value: 'Asia/Baghdad' },
  { label: 'Beirut - Lebanon', value: 'Asia/Beirut' },
  { label: 'Amman - Jordan', value: 'Asia/Amman' },
  { label: 'Tel Aviv - Israel', value: 'Asia/Jerusalem' },
  { label: 'Cairo - Egypt', value: 'Africa/Cairo' },
  { label: 'Cape Town - South Africa', value: 'Africa/Johannesburg' },
  { label: 'Johannesburg - South Africa', value: 'Africa/Johannesburg' },
  { label: 'Lagos - Nigeria', value: 'Africa/Lagos' },
  { label: 'Nairobi - Kenya', value: 'Africa/Nairobi' },
  { label: 'São Paulo - Brazil', value: 'America/Sao_Paulo' },
  { label: 'Buenos Aires - Argentina', value: 'America/Argentina/Buenos_Aires' },
  { label: 'Santiago - Chile', value: 'America/Santiago' },
  { label: 'Bogotá - Colombia', value: 'America/Bogota' },
  { label: 'Lima - Peru', value: 'America/Lima' },
  { label: 'Caracas - Venezuela', value: 'America/Caracas' },
  { label: 'Sydney - Australia', value: 'Australia/Sydney' },
  { label: 'Melbourne - Australia', value: 'Australia/Melbourne' },
  { label: 'Brisbane - Australia', value: 'Australia/Brisbane' },
  { label: 'Perth - Australia', value: 'Australia/Perth' },
  { label: 'Auckland - New Zealand', value: 'Pacific/Auckland' },
  { label: 'Wellington - New Zealand', value: 'Pacific/Auckland' },
  { label: 'Fiji', value: 'Pacific/Fiji' },
  { label: 'Samoa', value: 'Pacific/Samoa' },
];